## Lab 3: Hill Climbing

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# This is the Genetic Algoritms module by me
import GA

#### Encode the problem
* Each item is encoded with its: ( _benefit_, _volume_ )
* `CAPACITY` of the knapsack can be adjusted.
* `NUM_GENES` is the number of genes each individual has.

In [23]:
items = np.array([(5,3), (6,2), (1,4), (9,5), (2,8), (8,9), (4,10), (3,1), (7,6), (10,7)])
CAPACITY = 20
NUM_GENES = len(items)

#### Random Individual
* Generates a random individual with `length=10` number of genes.

In [24]:
GA.random_individual(10)

array([1, 1, 1, 1, 0, 1, 1, 0, 0, 1])

#### Random Population
* Generates a population with `population_size` number of individuals.
* Each individual will have `length` number of genes.

In [25]:
POPULATION_SIZE = 8
GA.random_population(POPULATION_SIZE, NUM_GENES)

[array([0, 0, 1, 0, 1, 0, 0, 0, 1, 0]),
 array([1, 0, 0, 1, 0, 0, 0, 1, 0, 1]),
 array([0, 0, 0, 1, 1, 1, 1, 0, 0, 0]),
 array([0, 1, 0, 1, 0, 0, 1, 1, 0, 1]),
 array([1, 0, 1, 1, 0, 1, 1, 0, 0, 1]),
 array([1, 0, 0, 0, 0, 1, 1, 0, 0, 1]),
 array([0, 0, 1, 1, 1, 0, 1, 0, 1, 0]),
 array([1, 0, 0, 1, 1, 0, 1, 0, 0, 1])]

#### Evaluate Individual
* Given an individual, returns the total benefit and total volume as a tuple.

In [6]:
individual_1 = GA.random_individual(10)
GA.evaluate_individual(individual_1)

(13, 8)

#### Mutate
* Given an individual, flip a random gene.

In [22]:
print(individual_1)
individual_2 = GA.mutate(individual_1)
print(individual_1)
print(individual_2)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0]


#### Mutate V2
* Flips each gene with probability `p`.

In [20]:
individual_1 = [0,0,0,0,0,0,0,0,0,0]
individual_2 = GA.mutate_v2(individual_1, 0.5)
print(individual_1)
print(individual_2)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 1, 1, 1, 0, 0]


#### Mutate Population
* Given a population, returns a new population where each gene is mutated. 
* Does not modify the original population.

In [ ]:
population1 = GA.random_population(POPULATION_SIZE, NUM_GENES);
print("Population[0] (before mutation): ", population1[0])

population2 = GA.mutate_population(population1)
print("Population[0] (after mutation):  ", population1[0])
print("New Population[0] :", population2[0])

#### Fitness
* Given an individual, evaluate its fitness.

In [ ]:
individual_1 = GA.random_individual(NUM_GENES)
GA.evaluate_individual(individual_1)
GA.fitness(individual_1)

### Random Search
* Generate individuals randomly, return the one with the highest fitness.
* Just a Baseline model

In [ ]:
GA.random_search(10000)

### Brute Force

Calculates the best solution to the problem by trying every possible combination.

In [ ]:
GA.brute_force()

### Single Hill Climber

In [ ]:
scores = GA.hill_climber(1000)
plt.xlabel("Generation")
plt.ylabel("Fitness")
plt.title("Single Hill Climber")
plt.plot(scores);

### Population of Hill Climbers

In [ ]:
GA.hill_climbers(20, 5000)